project:
  type: book
  output-dir: docs

engine: knitr 
lang: pt-br

book:
  title: "Criando Dashboards com Quarto"
  author: "Luís Gustavo Schuck"
  date: today
  chapters:
    - index.qmd
    - autor.qmd
    - intro.qmd
    - referencias.qmd

bibliography: referencias.bib

format:
  html:
    theme: cosmo
 

