project:
  type: book
  output-dir: docs

engine: knitr 
lang: pt-br

book:
  title: "Criando Dashboards com Quarto"
  author: "Luís Gustavo Schuck"
  date: today

  sidebar:
    collapse-level: 1
  repo-url: https://github.com/lgschuck/quarto_dashboard
  
  downloads: [pdf]

  chapters:
    - index.qmd
    - autor.qmd
    - intro.qmd
    - referencias.qmd

bibliography: referencias.bib

format:
  html:
    theme:
      light: [cosmo]
      dark: [slate]

  pdf:
    documentclass: scrreprt
 